// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/lasso/pkg/cache/sql/informer (interfaces: ByOptionsLister)

// Package sqlproxy is a generated GoMock package.
package sqlproxy

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	informer "github.com/rancher/lasso/pkg/cache/sql/informer"
	partition "github.com/rancher/lasso/pkg/cache/sql/partition"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// MockByOptionsLister is a mock of ByOptionsLister interface.
type MockByOptionsLister struct {
	ctrl     *gomock.Controller
	recorder *MockByOptionsListerMockRecorder
}

// MockByOptionsListerMockRecorder is the mock recorder for MockByOptionsLister.
type MockByOptionsListerMockRecorder struct {
	mock *MockByOptionsLister
}

// NewMockByOptionsLister creates a new mock instance.
func NewMockByOptionsLister(ctrl *gomock.Controller) *MockByOptionsLister {
	mock := &MockByOptionsLister{ctrl: ctrl}
	mock.recorder = &MockByOptionsListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockByOptionsLister) EXPECT() *MockByOptionsListerMockRecorder {
	return m.recorder
}

// ListByOptions mocks base method.
func (m *MockByOptionsLister) ListByOptions(arg0 context.Context, arg1 informer.ListOptions, arg2 []partition.Partition, arg3 string) (*unstructured.UnstructuredList, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOptions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*unstructured.UnstructuredList)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByOptions indicates an expected call of ListByOptions.
func (mr *MockByOptionsListerMockRecorder) ListByOptions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOptions", reflect.TypeOf((*MockByOptionsLister)(nil).ListByOptions), arg0, arg1, arg2, arg3)
}
