// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rancher/steve/pkg/sqlcache/informer (interfaces: ByOptionsLister)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -package informer -destination ./informer_mocks_test.go github.com/rancher/steve/pkg/sqlcache/informer ByOptionsLister
//

// Package informer is a generated GoMock package.
package informer

import (
	context "context"
	reflect "reflect"

	partition "github.com/rancher/steve/pkg/sqlcache/partition"
	sqltypes "github.com/rancher/steve/pkg/sqlcache/sqltypes"
	gomock "go.uber.org/mock/gomock"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// MockByOptionsLister is a mock of ByOptionsLister interface.
type MockByOptionsLister struct {
	ctrl     *gomock.Controller
	recorder *MockByOptionsListerMockRecorder
}

// MockByOptionsListerMockRecorder is the mock recorder for MockByOptionsLister.
type MockByOptionsListerMockRecorder struct {
	mock *MockByOptionsLister
}

// NewMockByOptionsLister creates a new mock instance.
func NewMockByOptionsLister(ctrl *gomock.Controller) *MockByOptionsLister {
	mock := &MockByOptionsLister{ctrl: ctrl}
	mock.recorder = &MockByOptionsListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockByOptionsLister) EXPECT() *MockByOptionsListerMockRecorder {
	return m.recorder
}

// ListByOptions mocks base method.
func (m *MockByOptionsLister) ListByOptions(arg0 context.Context, arg1 *sqltypes.ListOptions, arg2 []partition.Partition, arg3 string) (*unstructured.UnstructuredList, int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOptions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*unstructured.UnstructuredList)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListByOptions indicates an expected call of ListByOptions.
func (mr *MockByOptionsListerMockRecorder) ListByOptions(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOptions", reflect.TypeOf((*MockByOptionsLister)(nil).ListByOptions), arg0, arg1, arg2, arg3)
}

// SetFieldGetterForGroupName mocks base method.
func (m *MockByOptionsLister) SetFieldGetterForGroupName(arg0 func(arg0, arg1, arg2 string) [][]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFieldGetterForGroupName", arg0)
}

// SetFieldGetterForGroupName indicates an expected call of SetFieldGetterForGroupName.
func (mr *MockByOptionsListerMockRecorder) SetFieldGetterForGroupName(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFieldGetterForGroupName", reflect.TypeOf((*MockByOptionsLister)(nil).SetFieldGetterForGroupName), arg0)
}
