// Code generated by main. DO NOT EDIT.

// +k8s:openapi-gen=true
// +k8s:deepcopy-gen=package
// +groupName=testapis
package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// TestTypeList is a list of TestType resources
type TestTypeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []TestType `json:"items"`
}

func NewTestType(namespace, name string, obj TestType) *TestType {
	obj.APIVersion, obj.Kind = SchemeGroupVersion.WithKind("TestType").ToAPIVersionAndKind()
	obj.Name = name
	obj.Namespace = namespace
	return &obj
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// TestTypeOtherList is a list of TestTypeOther resources
type TestTypeOtherList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []TestTypeOther `json:"items"`
}

func NewTestTypeOther(namespace, name string, obj TestTypeOther) *TestTypeOther {
	obj.APIVersion, obj.Kind = SchemeGroupVersion.WithKind("TestTypeOther").ToAPIVersionAndKind()
	obj.Name = name
	obj.Namespace = namespace
	return &obj
}
