name: Backport

on:
  workflow_dispatch:
    inputs:
      pull-request:
        required: true
      target-branch:
        required: true
        default: "test-branch-for-backport"
      is-draft:
        type: boolean
        default: "false"

jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - run: |
          git config --global user.email "tom.lebreux@suse.com"
          git config --global user.name "Tom Lebreux <tom.lebreux@suse.com>"

      - uses: tomleb/gha-tests/backport@main
        with:
          pull-request: ${{ github.event.inputs.pull-request }}
          target-branch: ${{ github.event.inputs.target-branch }}
          repository: "${{ github.repository }}"
          is-draft: ${{ github.event.inputs.is-draft }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
