name: Backport

on:
  # Documentation for pull_request event: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
  pull_request:
    type: [labeled, closed]
    # So I remember to only run this on PRs targetting release branches
    # branches:
    # - main
    # - 'release/**'

jobs:
  backport:
    # For now, only run if the PR is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     persist-credentials: true
      #     fetch-depth: 0

      - run: |
          echo The labels are: ${{ github.event.pull_request.labels }}

      # - uses: tomleb/gha-tests/backport@main
      #   with:
      #     pull-request: ${{ github.event.inputs.pull-request }}
      #     target-branch: ${{ github.event.inputs.target-branch }}
      #     repository: "${{ github.repository }}"
      #     is-draft: ${{ github.event.inputs.is-draft }}
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
