name: Integration tests

on:
  pull_request: {}
  push:
    branches:
    - master
    - release/*

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout repository
      # https://github.com/actions/checkout/releases/tag/v4.1.1
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install Go
      # https://github.com/actions/setup-go/releases/tag/v5.0.0
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: 'go.mod'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

    - name: Install k3d
      run: |
        ./scripts/install-k3d.sh
        sudo mv ./bin/k3d /usr/local/bin/k3d

    - name: Download dependencies
      run: go mod download

    - name: Run integration tests
      run: make integration-tests
      env:
        INTEGRATION_TEST_ARGS: "-v -count=1"
